In [1]:
! pip install kaggle

Collecting kaggle
  Downloading kaggle-2.2.4-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: bleach in c:\users\shrav\anaconda3\lib\site-packages (from kaggle) (6.3.0)
Collecting jupytext (from kaggle)
  Downloading jupytext-1.19.5-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: kagglesdk<1.0,>=0.1.35 in c:\users\shrav\anaconda3\lib\site-packages (from kaggle) (0.1.37)
Requirement already satisfied: packaging in c:\users\shrav\anaconda3\lib\site-packages (from kaggle) (25.0)
Requirement already satisfied: protobuf in c:\users\shrav\anaconda3\lib\site-packages (from kaggle) (5.29.3)
Requirement already satisfied: python-dateutil in c:\users\shrav\anaconda3\lib\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-dotenv in c:\users\shrav\anaconda3\lib\site-packages (from kaggle) (1.1.0)
Requirement already satisfied: python-slugify in c:\users\shrav\anaconda3\lib\site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in c:\users\shrav\anaconda3\lib\site-packages (from kaggle) (2.32.5)
Requirement already satisfied: tqdm in c:\users\shrav\anaconda3\lib\site-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in c:\users\shrav\anaconda3\lib\site-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in c:\users\shrav\anaconda3\lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in c:\users\shrav\anaconda3\lib\site-packages (from jupytext->kaggle) (2.2.0)
Requirement already satisfied: mdit-py-plugins in c:\users\shrav\anaconda3\lib\site-packages (from jupytext->kaggle) (0.5.0)
Requirement already satisfied: nbformat in c:\users\shrav\anaconda3\lib\site-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in c:\users\shrav\anaconda3\lib\site-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: mdurl~=0.1 in c:\users\shrav\anaconda3\lib\site-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\shrav\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in c:\users\shrav\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (4.25.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\shrav\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (5.8.1)
Requirement already satisfied: traitlets>=5.1 in c:\users\shrav\anaconda3\lib\site-packages (from nbformat->jupytext->kaggle) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\shrav\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\shrav\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\shrav\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\shrav\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.28.0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\shrav\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.5.0)
Requirement already satisfied: pywin32>=300 in c:\users\shrav\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (311)
Requirement already satisfied: six>=1.5 in c:\users\shrav\anaconda3\lib\site-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\shrav\anaconda3\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\shrav\anaconda3\lib\site-packages (from requests->kaggle) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\shrav\anaconda3\lib\site-packages (from requests->kaggle) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\shrav\anaconda3\lib\site-packages (from requests->kaggle) (2025.11.12)
Requirement already satisfied: colorama in c:\users\shrav\anaconda3\lib\site-packages (from tqdm->kaggle) (0.4.6)
Downloading kaggle-2.2.4-py3-none-any.whl (126 kB)
Downloading jupytext-1.19.5-py3-none-any.whl (229 kB)
Installing collected packages: jupytext, kaggle

   ---------------------------------------- 0/2 [jupytext]
   -------------------- ------------------- 1/2 [kaggle]
   ---------------------------------------- 2/2 [kaggle]

Successfully installed jupytext-1.19.5 kaggle-2.2.4

In [4]:
import kaggle

In [5]:
!kaggle datasets download ankitbansal06/retail-orders -f orders.csv

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
Downloading orders.csv.zip to C:\Users\shrav\Documents\SQL+PYTHON

  0%|          | 0.00/200k [00:00<?, ?B/s]
100%|##########| 200k/200k [00:00<00:00, 766kB/s]
100%|##########| 200k/200k [00:00<00:00, 765kB/s]

In [6]:
import zipfile
zip_ref = zipfile.ZipFile('orders.csv.zip') 
zip_ref.extractall() # extract file to dir
zip_ref.close() # close file

In [18]:
import pandas as pd
df = pd.read_csv('orders.csv', na_values=['Not Available', 'unknown'])
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],
      dtype=object)

In [25]:
df.columns = df.columns.str.lower()

In [27]:
df.columns= df.columns.str.replace(' ', '_' )

In [28]:
df.columns

Index(['order_id', 'order_date', 'ship_mode', 'segment', 'country', 'city',
       'state', 'postal_code', 'region', 'category', 'sub_category',
       'product_id', 'cost_price', 'list_price', 'quantity',
       'discount_percent'],
      dtype='object')

In [29]:
df['discount'] = df['list_price']* df['discount_percent']*0.01

In [31]:
df['sale_price'] =  df['list_price'] -df['discount']

In [35]:
df['profit'] =  df['sale_price'] -df['cost_price']

In [42]:
df['order_date'] = pd.to_datetime(df['order_date'],format="%Y-%m-%d")

In [44]:
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8,22.8

In [43]:
df.dtypes

order_id                     int64
order_date          datetime64[ns]
ship_mode                   object
segment                     object
country                     object
city                        object
state                       object
postal_code                  int64
region                      object
category                    object
sub_category                object
product_id                  object
cost_price                   int64
list_price                   int64
quantity                     int64
discount_percent             int64
discount                   float64
sale_price                 float64
profit                     float64
dtype: object

In [47]:
df = df.drop(columns=['cost_price','list_price','discount_percent'])

In [48]:
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,3,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,2,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,4,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,2,7.2,232.8,22.8

In [63]:
df.head()

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0

In [67]:
df.dtypes

order_id                 int64
order_date      datetime64[ns]
ship_mode               object
segment                 object
country                 object
city                    object
state                   object
postal_code              int64
region                  object
category                object
sub_category            object
product_id              object
quantity                 int64
discount               float64
sale_price             float64
profit                 float64
dtype: object

In [68]:
import sqlalchemy as sal
engine = sal.create_engine('mssql+pyodbc://LAPTOP-135PO6B1/RetailStore?driver=ODBC+Driver+17+For+SQL+Server')
conn=engine.connect()

In [73]:
df.to_sql('df_orders', con=conn , index=False, if_exists = 'append')

38

In [71]:
df.columns

Index(['order_id', 'order_date', 'ship_mode', 'segment', 'country', 'city',
       'state', 'postal_code', 'region', 'category', 'sub_category',
       'product_id', 'quantity', 'discount', 'sale_price', 'profit'],
      dtype='object')